; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

; Global configuration that applies to all environments
[platformio]
default_envs = esp32-c3-debug

;	=====================
;	Shared configurations
;	=====================
; Dependencies for all device builds
[deps_app]
lib_deps =
    tzapu/WiFiManager@^2.0.17
    bblanchon/ArduinoJson@^7.4.3
    bblanchon/StreamUtils@^1.9.0

; Common configuration shared across environments
[env]
extends = deps_app
platform = espressif32@6.12.0
framework = arduino  ; Todo change to `espidf` for firmware encryption
monitor_speed = 115200
board_build.arduino.usb_mode = 0
board_build.arduino.usb_cdc_on_boot = 0
board_build.flash_size = 4MB
; Predefined Partition https://github.com/espressif/arduino-esp32/tree/master/tools/partitions
; 1,572,864 Bytes -> 1.5 Mb
; 1,360,656 firmware.bin
board_build.partitions = huge_app.csv
build_flags =
    -Os                     ; Optimize for size instead of -Og
    -ffunction-sections     ; Each function → separate section
    -fdata-sections         ; Each variable → separate section
    -Wl,--gc-sections       ; Remove unused sections at link time
    -Iinclude                ;telling the compiler to also look in the include/ folder at the project root.

; Custom data group
; can be use in [env:***] via ${common.***}
[common]
version_flag_dynamic = -D BUILD_TIME=$UNIX_TIME
                       !echo '-D FIRMWARE_VERSION=\\"'$(git describe --tags)'\\"'
version_flag_static = -D FIRMWARE_VERSION=\"v0.5.0-4-g7c0761b\"
production_flag = -D PRODUCTION=1
                  -D CORE_DEBUG_LEVEL=0
debug_flag = -D PRODUCTION=0
             -D CORE_DEBUG_LEVEL=4


[env:esp32-c3-base]
; 400 KB SRAM (16 KB for cache)
; 384 KB ROM
; 8 KB SRAM in RTC
; 4Mflash
extends = env
board = esp32-c3-devkitc-02
board_build.flash_size = 4MB
board_build.partitions = partition/4MB-ota.csv
build_flags =
    ${env.build_flags}
    -D BOARD_ESP32_C3

;	=====================
;	Each device configurations
;	=====================

; Debug environment with verbose logging
[env:esp32-c3-debug]
extends = env:esp32-c3-base
board_build.arduino.usb_mode = 1
board_build.arduino.usb_cdc_on_boot = 1
build_flags =
    ${env:esp32-c3-base.build_flags}
    ${common.version_flag_static}
    ${common.debug_flag}

; Release environment with minimal logging
[env:esp32-c3-production]
extends = env:esp32-c3-base
build_flags =
    ${env:esp32-c3-base.build_flags}
    ${common.version_flag_dynamic}
    ${common.production_flag}

